version: "3.9"

services:

  redis:
    image: redis
    ports:
    - '6379:6379'

  db:
    image: postgres
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB=choco_db
      - POSTGRES_USER=rainhunter_db
      - POSTGRES_PASSWORD=Rainhunter13?
    ports:
    - "5432:5432"

  web:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery_worker:
    build: .
    command: celery -A choco_project worker --loglevel=INFO -f logs/celery.logs
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A choco_project beat --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
      - db
