# Generated by Django 3.1.4 on 2021-01-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210108_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
