# Generated by Django 3.1.5 on 2021-01-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20210108_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mechta_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sulpak_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technodom_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='veter_price',
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(default='01.01.1991-00:00:00', max_length=100)),
                ('sulpak_price', models.IntegerField(default=-1)),
                ('technodom_price', models.IntegerField(default=-1)),
                ('mechta_price', models.IntegerField(default=-1)),
                ('veter_price', models.IntegerField(default=-1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.product')),
            ],
        ),
    ]
