# Generated by Django 3.1.5 on 2021-01-09 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20210109_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='myapi.product'),
        ),
    ]
