# Generated by Django 3.1.5 on 2021-01-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210109_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='date_time',
            field=models.CharField(default='01.01.70 00:00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='mechta_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='sulpak_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='technodom_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='veter_price',
            field=models.IntegerField(default=None),
        ),
    ]
