# Generated by Django 3.1.4 on 2021-01-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='no category', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='no name', max_length=500),
        ),
    ]
