# Generated by Django 3.1.5 on 2021-01-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210108_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='no description', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='mechta_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='sulpak_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='technodom_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='veter_price',
            field=models.IntegerField(default=-1),
        ),
    ]
