# Generated by Django 3.1.5 on 2021-01-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_auto_20210118_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_recording',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='myapi.pricerecording'),
        ),
    ]
