# Generated by Django 3.1.5 on 2021-01-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_auto_20210118_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='shop',
            new_name='seller',
        ),
    ]
